	graph LR
		A[Team A Google Group] -- Folder Admin/Owner -->AF[Team A folder]
		A1[Team A production Google Group] -- Folder Admin/Owner -->A1F[Team A production folder]
		A2[Team A production Google Group] -- Folder Admin/Owner -->A2F[Team A staging folder]
		P[playground Google Group] -- Folder Admin/Owner -->PF[Team B playground folder]
