	graph LR
		R[Organization root] --> A[Team A folder]
		R[Organization root] --> B[Team B folder]
		A[Company folder] --> A1[Team A production folder]
		A[Company folder] --> A2[Team A staging folder]
		B[Company folder] --> B1[Team B production folder]
		B[Company folder] --> B2[Team B staging folder]
		R[Organization root] --> P[playground folder]
