	graph LR
		R[Organization root] --> C[Company OU]
		C[Company OU] --> A1[Team A production AWS account]
		C[Company OU] --> A2[Team A staging AWS account]
		C[Company OU] --> B1[Team B production AWS account]
		C[Company OU] --> B2[Team B staging AWS account]
		R[Organization root] --> P[playground AWS account]
