	graph LR;
		A[A AWS account admin group] --> AA[Administer role of A account];
		A[A AWS account readonly group] --> AR[readonly role of account];
		B[B AWS account admin group] --> BA[Administer role of A account];
		B[B AWS account readonly group] --> BR[readonly role of account];
