import { readFileSync, writeFileSync } from "node:fs";

const tokens = JSON.parse(readFileSync("docs/theme/tokens.json", "utf8"));

const entries = o =>
  Object.entries(o).filter(([name]) => !name.startsWith("_"));

const palette = (world, indent) =>
  entries(tokens[world])
    .map(([name, value]) => `${indent}${name}: ${value};`)
    .join("\n");

const syntax = (world, indent) =>
  entries(tokens.syntax[world])
    .map(([name, value]) => `${indent}--syn-${name}: ${value};`)
    .join("\n");

const block = (world, indent) =>
  `${palette(world, indent)}\n${syntax(world, indent)}`;

const css = `/* GENERATED by scripts/build-tokens.mjs from docs/theme/tokens.json.
   Do not edit by hand — edit the JSON and re-run \`npm run build:tokens\`.
   Torchlight ${tokens.version}. Bare :root is the hollowed world. */

:root {
${block("hollowed", "  ")}
}

@media (prefers-color-scheme: light) {
  :root:not([data-theme="dark"]):not([data-theme="hollowed"]) {
${block("kindled", "    ")}
  }
}

:root[data-theme="light"],
:root[data-theme="kindled"] {
${block("kindled", "  ")}
}
`;

writeFileSync("src/styles/tokens.css", css);
console.log(`tokens.css written (${tokens.name} ${tokens.version})`);
